# file: R/z_rcs.R
#' z_rcs: thin, user-friendly alias of plotRCS::rcsplot()
#'
#' @description
#' A convenience wrapper of \code{plotRCS::rcsplot()} that keeps **all**
#' functionalities of the original function (via \code{...}) while exposing a
#' minimal set of frequently used arguments. If \code{df} is provided and
#' \code{knots} is missing, knots will be generated by \code{plotRCS::knot(df)}.
#' The argument \code{conf_int} is accepted and mapped to \code{conf.int}.
#'
#' @param data A data.frame/data.table (same as \code{rcsplot}).
#' @param outcome,time,exposure,covariates Same semantics as \code{rcsplot}.
#' @param df Integer degrees of freedom for knots; if provided while \code{knots}
#'   is missing, \code{knots <- plotRCS::knot(df)}.
#' @param knots Knot locations (same as \code{rcsplot}).
#' @param ref.value Reference value (numeric or "min"/"median"/"mean"/"k1"/"k2"/...),
#'   passed to \code{rcsplot}.
#' @param linecolor Line color (same as \code{rcsplot}).
#' @param conf_int Logical; alias of \code{conf.int}.
#' @param ... Any other arguments of \code{plotRCS::rcsplot()} are forwarded
#'   unchanged (e.g., \code{positive, group, knots.line, ref.line, conf.level,
#'   conf.type, pvalue, pvalue.digits, pvalue.position, pvalue.label.overall,
#'   pvalue.label.nonlinear, fontsize, fontfamily, linesize, alpha, xbreaks,
#'   ybreaks, xlab, ylab, explain, log, survey.design, weights}, etc.).
#'
#' @return A \code{ggplot2} object with class \code{'rcsplot'} (identical to \code{rcsplot}).
#'
#' @examples
#' \dontrun{
#' # Minimal usage with key arguments only:
#' p <- z_rcs(
#' data = dt,
#' outcome = "all_cause_status",
#' time = "all_cause_time",
#' exposure = "twa_benzene",
#' covariates = c("gender","ethnicity"),
#' df = 4,                              # or knots = plotRCS::knot(4)
#' ref.value = median(dt$twa_benzene, na.rm = TRUE),
#' linecolor = "#4f4f4f",
#' linesize=0.5
#' )
#' 
#' p <- z_rcs(
#'   data = dt,
#'   outcome = "all_cause_status",
#'   time = "all_cause_time",
#'   exposure = "twa_benzene",
#'   covariates = c("gender","ethnicity"),
#'   df = 4,                              # or knots = plotRCS::knot(4)
#'   ref.value = median(dt$twa_benzene, na.rm = TRUE),
#'   linecolor = "red",
#'   conf_int = TRUE                      # alias of conf.int
#' )
#' print(p)
#'
#' # Full power still available via ...:
#' p <- z_rcs(
#'   data = dt, outcome = "status", time = "time", exposure = "age",
#'   covariates = c("sex","race"),
#'   knots = plotRCS::knot(5),
#'   ref.value = "k2",
#'   pvalue = TRUE, pvalue.digits = 2, pvalue.position = c(0.05, 0.95),
#'   fontsize = 13, fontfamily = "serif"
#' )
#' }
#' @seealso \code{\link[plotRCS]{rcsplot}}, \code{\link[plotRCS]{knot}}
#' @export
#' @importFrom plotRCS rcsplot knot
z_rcs <- function(
    data,
    outcome = NULL,
    time = NULL,
    exposure = NULL,
    covariates = NULL,
    df = NULL,
    knots = NULL,
    ref.value = "k1",
    linecolor = "#0072B5FF",
    conf_int = NULL,
    ...
) {
  if (!requireNamespace("plotRCS", quietly = TRUE)) {
    stop("Package 'plotRCS' is required. Install with: install.packages('plotRCS')")
  }
  # Basic sanity check to reduce易错点
  if (!missing(data) && !is.data.frame(data) && !"data.table" %in% class(data)) {
    stop("`data` must be a data.frame/data.table")
  }
  # df -> knots (only if user didn't supply knots)
  if (is.null(knots) && !is.null(df)) {
    if (!is.numeric(df) || length(df) != 1L || df < 2) {
      stop("`df` must be a single integer >= 2 when used to derive knots.")
    }
    knots <- plotRCS::knot(as.integer(df))
  }
  # Allow conf_int alias (if provided, override conf.int default behavior)
  dotlist <- list(...)
  if (!is.null(conf_int) && is.logical(conf_int)) {
    dotlist$conf.int <- conf_int
  }
  # Build argument list to forward (keep original API intact)
  args <- c(
    list(
      data = data,
      outcome = outcome,
      time = time,
      exposure = exposure,
      covariates = covariates,
      knots = knots,
      ref.value = ref.value,
      linecolor = linecolor
    ),
    dotlist
  )
  # Call underlying function and return its ggplot
  out <- do.call(plotRCS::rcsplot, args)
  out
}
